"""initial

Revision ID: 9b83083e9f75
Revises: 
Create Date: 2025-12-07 22:51:10.466088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b83083e9f75'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_documents', 'doc_type',
               existing_type=postgresql.ENUM('RESUME', 'COVER_LETTER', name='documenttypeenum'),
               type_=sa.Enum('RESUME', 'COVER_LETTER', name='documenttypeenum', native_enum=False),
               existing_nullable=False)
    op.drop_constraint(op.f('llm_settings_user_id_key'), 'llm_settings', type_='unique')
    op.alter_column('search_filters', 'employment',
               existing_type=postgresql.ENUM('FULL', 'PART', 'INTERNSHIP', 'PROJECT', name='employmenttypeenum'),
               type_=sa.Enum('FULL', 'PART', 'INTERNSHIP', 'PROJECT', name='employmenttypeenum', native_enum=False),
               existing_nullable=True)
    op.alter_column('search_filters', 'experience',
               existing_type=postgresql.ENUM('NO_EXPERIENCE', 'BETWEEN_1_AND_3', 'BETWEEN_3_AND_6', 'MORE_THAN_6', name='experienceenum'),
               type_=sa.Enum('NO_EXPERIENCE', 'BETWEEN_1_AND_3', 'BETWEEN_3_AND_6', 'MORE_THAN_6', name='experienceenum', native_enum=False),
               existing_nullable=True)
    op.add_column('user_vacancy_status', sa.Column('status', sa.Enum('SENT', 'VIEWED', 'NOT_INTERESTED', name='uservacancystatusenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_vacancy_status', 'status')
    op.alter_column('search_filters', 'experience',
               existing_type=sa.Enum('NO_EXPERIENCE', 'BETWEEN_1_AND_3', 'BETWEEN_3_AND_6', 'MORE_THAN_6', name='experienceenum', native_enum=False),
               type_=postgresql.ENUM('NO_EXPERIENCE', 'BETWEEN_1_AND_3', 'BETWEEN_3_AND_6', 'MORE_THAN_6', name='experienceenum'),
               existing_nullable=True)
    op.alter_column('search_filters', 'employment',
               existing_type=sa.Enum('FULL', 'PART', 'INTERNSHIP', 'PROJECT', name='employmenttypeenum', native_enum=False),
               type_=postgresql.ENUM('FULL', 'PART', 'INTERNSHIP', 'PROJECT', name='employmenttypeenum'),
               existing_nullable=True)
    op.create_unique_constraint(op.f('llm_settings_user_id_key'), 'llm_settings', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('generated_documents', 'doc_type',
               existing_type=sa.Enum('RESUME', 'COVER_LETTER', name='documenttypeenum', native_enum=False),
               type_=postgresql.ENUM('RESUME', 'COVER_LETTER', name='documenttypeenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
